# Generated by Django 3.2.25 on 2026-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'RRHH'), ('2', 'Inventario'), ('3', 'Empleado'), ('4', 'Ventas')], default='3', max_length=1, verbose_name='Rol'),
        ),
    ]
